# Generated by Django 5.2.8 on 2026-02-05 07:57

import django.db.models.deletion
import nexgensis_forms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=nexgensis_forms.models.uuid7_default, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('validation_rules', models.JSONField(blank=True, help_text='Validation rules for the data type', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('effective_end_date', models.DateTimeField(blank=True, null=True)),
                ('previous_version_id', models.UUIDField(blank=True, null=True)),
                ('unique_code', models.CharField(blank=True, max_length=50)),
                ('id', models.UUIDField(default=nexgensis_forms.models.uuid7_default, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=nexgensis_forms.models.uuid7_default, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('dynamic', models.BooleanField(default=False, help_text='Is this field type dynamic?')),
                ('endpoint', models.CharField(blank=True, help_text='API endpoint for dynamic field types', max_length=255, null=True)),
                ('validation_rules', models.JSONField(blank=True, help_text='Validation rules for the field type', null=True)),
                ('default', models.BooleanField(default=False, help_text='Is this field type the default for its data type?')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_types', to='nexgensis_forms.datatype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('effective_end_date', models.DateTimeField(blank=True, null=True)),
                ('previous_version_id', models.UUIDField(blank=True, null=True)),
                ('unique_code', models.CharField(blank=True, max_length=50)),
                ('id', models.UUIDField(default=nexgensis_forms.models.uuid7_default, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('effective_end_date', models.DateTimeField(blank=True, null=True)),
                ('previous_version_id', models.UUIDField(blank=True, null=True)),
                ('unique_code', models.CharField(blank=True, max_length=50)),
                ('id', models.UUIDField(default=nexgensis_forms.models.uuid7_default, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location_id', models.CharField(blank=True, help_text='Location identifier (optional)', max_length=255, null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Is the form completed?')),
                ('version', models.PositiveIntegerField(default=1)),
                ('system_config', models.JSONField(blank=True, default=dict)),
                ('user_config', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('criteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='nexgensis_forms.criteria')),
                ('parent_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_forms', to='nexgensis_forms.form')),
                ('root_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='nexgensis_forms.form')),
            ],
        ),
        migrations.CreateModel(
            name='FormDraft',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=nexgensis_forms.models.uuid7_default, editable=False, primary_key=True, serialize=False)),
                ('draft_data', models.JSONField(blank=True, help_text='Draft data for the form', null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexgensis_forms.form')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormSections',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=nexgensis_forms.models.uuid7_default, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the section in the form')),
                ('dependency', models.JSONField(blank=True, help_text='Section dependency configuration', null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexgensis_forms.form')),
            ],
        ),
        migrations.CreateModel(
            name='FormFields',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=nexgensis_forms.models.uuid7_default, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the fields in the form')),
                ('additional_info', models.JSONField(blank=True, help_text='Additional values for the data type', null=True)),
                ('dependency', models.JSONField(blank=True, help_text='Field dependency configuration', null=True)),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nexgensis_forms.fieldtype')),
                ('parent_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_fields', to='nexgensis_forms.formfields')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexgensis_forms.formsections')),
            ],
        ),
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('effective_end_date', models.DateTimeField(blank=True, null=True)),
                ('previous_version_id', models.UUIDField(blank=True, null=True)),
                ('unique_code', models.CharField(blank=True, max_length=50)),
                ('id', models.UUIDField(default=nexgensis_forms.models.uuid7_default, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent_form_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_forms', to='nexgensis_forms.formtype')),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='form_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexgensis_forms.formtype'),
        ),
        migrations.CreateModel(
            name='MainProcess',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('effective_end_date', models.DateTimeField(blank=True, null=True)),
                ('previous_version_id', models.UUIDField(blank=True, null=True)),
                ('unique_code', models.CharField(blank=True, max_length=50)),
                ('id', models.UUIDField(default=nexgensis_forms.models.uuid7_default, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='main_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='nexgensis_forms.mainprocess'),
        ),
        migrations.AddConstraint(
            model_name='criteria',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_end_date__isnull', True)), fields=('unique_code',), name='unique_active_criteria_code'),
        ),
        migrations.AddConstraint(
            model_name='focusarea',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_end_date__isnull', True)), fields=('unique_code',), name='unique_active_focusarea_code'),
        ),
        migrations.AlterUniqueTogether(
            name='formsections',
            unique_together={('form', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='formfields',
            unique_together={('label', 'section', 'parent_field')},
        ),
        migrations.AddConstraint(
            model_name='formtype',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_end_date__isnull', True)), fields=('unique_code',), name='unique_active_formtype_code'),
        ),
        migrations.AddConstraint(
            model_name='mainprocess',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_end_date__isnull', True)), fields=('unique_code',), name='unique_active_mainprocess_code'),
        ),
        migrations.AddConstraint(
            model_name='form',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_end_date__isnull', True)), fields=('unique_code',), name='unique_active_form_code'),
        ),
    ]
